CREATE TABLE forms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL,
  status TEXT NOT NULL,
  title TEXT NOT NULL,
  session_name TEXT,
  description TEXT,
  date DATE,
  closing TIMESTAMPTZ,
  closing_text TEXT,
  total_expected INTEGER NOT NULL DEFAULT 0,
  labels_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  field_definitions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  results_config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  scale_sections_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_forms_status ON forms(status);
CREATE INDEX idx_forms_type ON forms(type);

CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  date DATE,
  opening TIMESTAMPTZ,
  closing TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'rascunho',
  form_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  eligible_graus_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  message_config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_events_status ON events(status);
CREATE INDEX idx_events_date ON events(date);

CREATE TABLE responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id BIGINT NOT NULL REFERENCES forms(id) ON DELETE CASCADE,
  respondent_name TEXT NOT NULL,
  respondent_grau TEXT,
  respondent_key TEXT NOT NULL,
  person_key TEXT,
  values_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (form_id, respondent_key)
);

CREATE INDEX idx_responses_person_key ON responses(person_key);

CREATE TABLE escala_assignments (
  form_id BIGINT PRIMARY KEY REFERENCES forms(id) ON DELETE CASCADE,
  sections_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE event_participation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  form_id BIGINT REFERENCES forms(id) ON DELETE CASCADE,
  person_key TEXT NOT NULL,
  person_name TEXT NOT NULL,
  grau TEXT,
  expected BOOLEAN NOT NULL DEFAULT TRUE,
  filled BOOLEAN NOT NULL DEFAULT FALSE,
  responded_at TIMESTAMPTZ,
  time_to_fill_minutes INTEGER,
  exemption_reason TEXT NOT NULL DEFAULT '',
  captured_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_event_participation_event ON event_participation(event_id);
CREATE INDEX idx_event_participation_person ON event_participation(person_key);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  password_hash TEXT,
  password_salt TEXT,
  password_algorithm TEXT,
  password_iterations INTEGER,
  password_migrated_at TIMESTAMPTZ,
  role TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE labels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT NOT NULL,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE presets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  closing_text TEXT,
  labels_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  field_definitions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  results_config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  scale_sections_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE people (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  grau TEXT,
  phone TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  source TEXT NOT NULL DEFAULT 'manual',
  external_key TEXT,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_people_name_lower ON people ((lower(name)));
CREATE INDEX idx_people_external_key ON people(external_key);

CREATE TABLE team_periods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  assistant_master_person_id BIGINT NOT NULL REFERENCES people(id),
  organ_person_id BIGINT NOT NULL REFERENCES people(id),
  direct_assistant_person_id BIGINT NOT NULL REFERENCES people(id),
  organ_direct_assistant_person_id BIGINT REFERENCES people(id),
  assistant_member_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  organ_member_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_team_periods_dates ON team_periods(start_date, end_date);

CREATE TABLE settings (
  key TEXT PRIMARY KEY,
  value_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE auth_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  last_used_at TIMESTAMPTZ
);

CREATE INDEX idx_auth_sessions_user_id ON auth_sessions(user_id);
CREATE INDEX idx_auth_sessions_expires_at ON auth_sessions(expires_at);

CREATE TABLE field_catalog (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  category TEXT NOT NULL,
  default_label TEXT NOT NULL,
  grid_schema_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  selection_source_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  description TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE scale_task_catalog (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  default_label TEXT NOT NULL,
  description TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE response_values (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  response_id BIGINT NOT NULL REFERENCES responses(id) ON DELETE CASCADE,
  form_id BIGINT NOT NULL REFERENCES forms(id) ON DELETE CASCADE,
  field_id TEXT NOT NULL,
  field_type TEXT,
  value_text TEXT,
  value_number DOUBLE PRECISION,
  value_boolean BOOLEAN,
  value_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (response_id, field_id)
);

CREATE INDEX idx_response_values_form_id ON response_values(form_id);

CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL,
  level TEXT NOT NULL,
  category TEXT NOT NULL,
  action TEXT NOT NULL,
  status TEXT NOT NULL,
  screen TEXT,
  actor_id BIGINT,
  actor_name TEXT,
  actor_role TEXT,
  entity_type TEXT,
  entity_id TEXT,
  entity_label TEXT,
  message TEXT,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  request_id TEXT,
  ip_address TEXT,
  user_agent TEXT
);

CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at DESC, id DESC);
CREATE INDEX idx_audit_logs_category_created_at ON audit_logs(category, created_at DESC);
CREATE INDEX idx_audit_logs_action_created_at ON audit_logs(action, created_at DESC);
CREATE INDEX idx_audit_logs_status_created_at ON audit_logs(status, created_at DESC);
CREATE INDEX idx_audit_logs_actor_name_created_at ON audit_logs(actor_name, created_at DESC);
CREATE INDEX idx_audit_logs_entity_type_created_at ON audit_logs(entity_type, created_at DESC);

CREATE TABLE message_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_message_templates_type ON message_templates(type);

CREATE TABLE person_selection_presets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  person_keys_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE event_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  template_id BIGINT REFERENCES message_templates(id) ON DELETE SET NULL,
  body TEXT NOT NULL,
  config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  scheduled_for TIMESTAMPTZ,
  window_option TEXT,
  auto_dispatch_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  status TEXT NOT NULL DEFAULT 'rascunho',
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_event_messages_event_id ON event_messages(event_id);
CREATE INDEX idx_event_messages_status_scheduled ON event_messages(status, scheduled_for);

CREATE TABLE message_dispatch_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id BIGINT NOT NULL REFERENCES event_messages(id) ON DELETE CASCADE,
  dispatched_at TIMESTAMPTZ NOT NULL,
  mode TEXT NOT NULL,
  rendered_body TEXT NOT NULL,
  recipients_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  group_name TEXT,
  status TEXT NOT NULL DEFAULT 'logged_only',
  dispatcher_version TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_message_dispatch_log_message_id ON message_dispatch_log(message_id);

CREATE TABLE schema_migrations (
  version INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  applied_at TIMESTAMPTZ NOT NULL
);
