/**
 * @file frontend/src/lib/appControllerInputs.js
 * @summary Montagem dos inputs internos do controller do App.
 */

export const buildAppControllerDerivedInput = values => ({
  bootstrap: values.bootstrap,
  responseDetails: values.responseDetails,
  escalaDetails: values.escalaDetails,
  currentUser: values.currentUser,
  pinnedFormsByUser: values.pinnedFormsByUser,
  pinnedEventsByUser: values.pinnedEventsByUser,
  activeFormId: values.activeFormId,
  activeEventId: values.activeEventId,
  editingFormId: values.editingFormId,
  draftForm: values.draftForm,
  publicRoute: values.publicRoute,
});

export const buildAppControllerLoadersInput = ({ values, setters }) => ({
  activeFormId: values.activeFormId,
  bootstrap: values.bootstrap,
  currentUser: values.currentUser,
  detailLoading: values.detailLoading,
  escalaDetails: values.escalaDetails,
  responseDetails: values.responseDetails,
  setActiveFormId: setters.setActiveFormId,
  setBootstrap: setters.setBootstrap,
  setDetailLoading: setters.setDetailLoading,
  setError: setters.setError,
  setEscalaDetails: setters.setEscalaDetails,
  setFormDeleteKeyConfigured: setters.setFormDeleteKeyConfigured,
  setLoading: setters.setLoading,
  setResponseDetails: setters.setResponseDetails,
});

export const buildAppControllerHandlersInput = ({
  bootstrapData,
  derived,
  loaders,
  setters,
  values,
}) => ({
  activeForm: derived.activeForm,
  activeEventId: values.activeEventId,
  currentUser: values.currentUser,
  events: bootstrapData.events,
  refreshBootstrap: loaders.refreshBootstrap,
  refreshEscalaForForm: loaders.refreshEscalaForForm,
  setActiveEventId: setters.setActiveEventId,
  setActiveFormId: setters.setActiveFormId,
  setActiveMessageId: setters.setActiveMessageId,
  setBootstrap: setters.setBootstrap,
  setDraftForm: setters.setDraftForm,
  setEditingFormId: setters.setEditingFormId,
  setEscalaDetails: setters.setEscalaDetails,
  setFontScale: setters.setFontScale,
  setFormDeleteKeyConfigured: setters.setFormDeleteKeyConfigured,
  setPinnedEventsByUser: setters.setPinnedEventsByUser,
  setPinnedFormsByUser: setters.setPinnedFormsByUser,
  setResponseDetails: setters.setResponseDetails,
  setScreen: setters.setScreen,
  setSession: setters.setSession,
});

export const buildAppControllerLifecycleInput = ({
  derived,
  loaders,
  sessionHandlers,
  setters,
  values,
}) => ({
  activeForm: derived.activeForm,
  authToken: values.authToken,
  currentUser: values.currentUser,
  detailLoading: values.detailLoading,
  error: values.error,
  escalaByForm: derived.escalaByForm,
  fontScale: values.fontScale,
  invalidateSession: sessionHandlers.invalidateSession,
  loadEscalaForForm: loaders.loadEscalaForForm,
  loadResponsesForForm: loaders.loadResponsesForForm,
  pinnedEventsByUser: values.pinnedEventsByUser,
  pinnedFormsByUser: values.pinnedFormsByUser,
  publicForm: derived.publicForm,
  publicResultsView: derived.publicResultsView,
  refreshBootstrap: loaders.refreshBootstrap,
  refreshFormDeleteKeyStatus: loaders.refreshFormDeleteKeyStatus,
  responsesByForm: derived.responsesByForm,
  screen: values.screen,
  session: values.session,
  setFontScale: setters.setFontScale,
  setPublicRoute: setters.setPublicRoute,
  setScreen: setters.setScreen,
  setSession: setters.setSession,
  setTheme: setters.setTheme,
  theme: values.theme,
});

export const buildAppControllerViewModelInput = ({
  bootstrapData,
  canCreateForms,
  derived,
  handlers,
  loaders,
  navigate,
  sessionHandlers,
  setters,
  values,
}) => ({
  adminHandlers: handlers.adminHandlers,
  activeEvent: derived.activeEvent,
  activeEventId: values.activeEventId,
  activeForm: derived.activeForm,
  activeMessageId: values.activeMessageId,
  canCreateForms,
  currentUser: values.currentUser,
  draftForm: values.draftForm,
  editingForm: derived.editingForm,
  error: values.error,
  escalaByForm: derived.escalaByForm,
  eventHandlers: handlers.eventHandlers,
  events: bootstrapData.events,
  externalBases: bootstrapData.externalBases,
  fieldCatalog: bootstrapData.fieldCatalog,
  fontScale: values.fontScale,
  formDeleteKeyConfigured: values.formDeleteKeyConfigured,
  formHandlers: handlers.formHandlers,
  forms: derived.forms,
  labels: bootstrapData.labels,
  loading: values.loading,
  membersConfig: bootstrapData.membersConfig,
  messageTemplates: bootstrapData.messageTemplates,
  messagingConfig: bootstrapData.messagingConfig,
  navigate,
  people: bootstrapData.people,
  personPresets: bootstrapData.personPresets,
  pinnedEventIds: derived.pinnedEventIds,
  pinnedFormIds: derived.pinnedFormIds,
  presets: bootstrapData.presets,
  publicForm: derived.publicForm,
  publicResultsEnabled: derived.publicResultsEnabled,
  publicResultsView: derived.publicResultsView,
  publicRoute: values.publicRoute,
  refreshBootstrap: loaders.refreshBootstrap,
  responsesByForm: derived.responsesByForm,
  scaleTaskCatalog: bootstrapData.scaleTaskCatalog,
  screen: values.screen,
  sessionHandlers,
  setActiveEventId: setters.setActiveEventId,
  setActiveFormId: setters.setActiveFormId,
  setActiveMessageId: setters.setActiveMessageId,
  setDraftForm: setters.setDraftForm,
  setEditingFormId: setters.setEditingFormId,
  setPublicRoute: setters.setPublicRoute,
  setScreen: setters.setScreen,
  setTheme: setters.setTheme,
  theme: values.theme,
  users: bootstrapData.users,
});
