import { CONTROLLER_VIEWMODEL_SETTER_KEYS, CONTROLLER_VIEWMODEL_VALUE_KEYS } from "./appControllerInputKeys";

const pick = (source, keys) => keys.reduce((picked, key) => ({
  ...picked,
  [key]: source[key],
}), {});

export const buildAppControllerViewModelInput = ({
  bootstrapData,
  canCreateForms,
  derived,
  handlers,
  loaders,
  navigate,
  sessionHandlers,
  setters,
  values,
}) => ({
  adminHandlers: handlers.adminHandlers,
  activeEvent: derived.activeEvent,
  activeForm: derived.activeForm,
  canCreateForms,
  editingForm: derived.editingForm,
  escalaByForm: derived.escalaByForm,
  eventHandlers: handlers.eventHandlers,
  events: bootstrapData.events,
  externalBases: bootstrapData.externalBases,
  fieldCatalog: bootstrapData.fieldCatalog,
  formHandlers: handlers.formHandlers,
  forms: derived.forms,
  labels: bootstrapData.labels,
  membersConfig: bootstrapData.membersConfig,
  messageTemplates: bootstrapData.messageTemplates,
  messagingConfig: bootstrapData.messagingConfig,
  navigate,
  people: bootstrapData.people,
  personPresets: bootstrapData.personPresets,
  pinnedEventIds: derived.pinnedEventIds,
  pinnedFormIds: derived.pinnedFormIds,
  presets: bootstrapData.presets,
  publicForm: derived.publicForm,
  publicResultsEnabled: derived.publicResultsEnabled,
  publicResultsView: derived.publicResultsView,
  refreshBootstrap: loaders.refreshBootstrap,
  responsesByForm: derived.responsesByForm,
  scaleTaskCatalog: bootstrapData.scaleTaskCatalog,
  sessionHandlers,
  users: bootstrapData.users,
  ...pick(values, CONTROLLER_VIEWMODEL_VALUE_KEYS),
  ...pick(setters, CONTROLLER_VIEWMODEL_SETTER_KEYS),
});
