/**
 * @file frontend/src/lib/appControllerViewModel.js
 * @summary Montagem final do shell app e das props do viewport.
 */

import { buildAppShell, buildAppShellData, buildAppShellState } from "./appShellBuilder";
import { buildAppViewportProps } from "./appViewportProps";

export const buildAppControllerViewModel = ({
  adminHandlers,
  activeEvent,
  activeEventId,
  activeForm,
  activeMessageId,
  canCreateForms,
  currentUser,
  draftForm,
  editingForm,
  error,
  escalaByForm,
  events,
  externalBases,
  fieldCatalog,
  fontScale,
  formDeleteKeyConfigured,
  formHandlers,
  forms,
  labels,
  loading,
  membersConfig,
  messageTemplates,
  messagingConfig,
  navigate,
  people,
  personPresets,
  pinnedEventIds,
  pinnedFormIds,
  presets,
  publicForm,
  publicResultsEnabled,
  publicResultsView,
  publicRoute,
  refreshBootstrap,
  responsesByForm,
  scaleTaskCatalog,
  screen,
  sessionHandlers,
  setActiveEventId,
  setActiveFormId,
  setActiveMessageId,
  setDraftForm,
  setEditingFormId,
  setPublicRoute,
  setScreen,
  setTheme,
  theme,
  users,
  eventHandlers,
}) => {
  const shellApp = buildAppShell({
    adminHandlers,
    canCreateForms,
    currentUser,
    data: buildAppShellData({
      forms,
      labels,
      people,
      presets,
      fieldCatalog,
      scaleTaskCatalog,
      events,
      messageTemplates,
      personPresets,
      messagingConfig,
      membersConfig,
      externalBases,
      users,
      responsesByForm,
      escalaByForm,
    }),
    eventHandlers,
    formDeleteKeyConfigured,
    formHandlers,
    navigate,
    sessionHandlers,
    setActiveEventId,
    setActiveFormId,
    setActiveMessageId,
    setDraftForm,
    setEditingFormId,
    setScreen,
    setTheme,
    state: buildAppShellState({
      screen,
      fontScale,
      publicForm,
      publicRoute,
      publicResultsEnabled,
      publicResultsView,
      pinnedEventIds,
      pinnedFormIds,
      activeEventId,
      activeMessageId,
      activeEvent,
      activeForm,
      editingForm,
      draftForm,
    }),
    theme,
  });

  return buildAppViewportProps({
    app: shellApp,
    error,
    fontScale,
    loading,
    refreshBootstrap,
    sessionHandlers,
    setPublicRoute,
    setScreen,
    setTheme,
    theme,
  });
};
