/**
 * @file frontend/src/lib/appController.js
 * @summary Controller de alto nivel do App.
 * @responsibility Centralizar estado, handlers, efeitos e props do viewport fora de App.jsx.
 */

import { canCreateForms } from "./auth";
import { useAppControllerState } from "./appControllerState";
import { useAppControllerDerivedState } from "./appControllerDerived";
import { buildAppControllerViewModel } from "./appControllerViewModel";
import { buildAppControllerLoaders } from "./appControllerLoaders";
import { buildAppControllerHandlers } from "./appControllerHandlers";
import { useAppControllerLifecycle } from "./appControllerLifecycle";

export const useAppController = () => {
  const { values, setters } = useAppControllerState();
  const {
    activeEventId,
    activeFormId,
    activeMessageId,
    authToken,
    bootstrap,
    currentUser,
    detailLoading,
    draftForm,
    editingFormId,
    error,
    escalaDetails,
    fontScale,
    formDeleteKeyConfigured,
    loading,
    pinnedEventsByUser,
    pinnedFormsByUser,
    publicRoute,
    responseDetails,
    screen,
    session,
    theme,
  } = values;
  const {
    setActiveEventId,
    setActiveFormId,
    setActiveMessageId,
    setBootstrap,
    setDetailLoading,
    setDraftForm,
    setEditingFormId,
    setError,
    setEscalaDetails,
    setFontScale,
    setFormDeleteKeyConfigured,
    setLoading,
    setPinnedEventsByUser,
    setPinnedFormsByUser,
    setPublicRoute,
    setResponseDetails,
    setScreen,
    setSession,
    setTheme,
  } = setters;
  const { users, labels, presets, fieldCatalog, scaleTaskCatalog, people, membersConfig, externalBases, events, messageTemplates = [], personPresets = [], messagingConfig = { whatsappGroupName: "", autoDispatchEnabled: true, publicBaseUrl: "" } } = bootstrap;
  const {
    forms,
    responsesByForm,
    escalaByForm,
    pinnedFormIds,
    pinnedEventIds,
    activeForm,
    activeEvent,
    editingForm,
    publicForm,
    publicResultsEnabled,
    publicResultsView,
  } = useAppControllerDerivedState({
    bootstrap,
    responseDetails,
    escalaDetails,
    currentUser,
    pinnedFormsByUser,
    pinnedEventsByUser,
    activeFormId,
    activeEventId,
    editingFormId,
    draftForm,
    publicRoute,
  });
  const {
    loadEscalaForForm,
    loadResponsesForForm,
    refreshBootstrap,
    refreshEscalaForForm,
    refreshFormDeleteKeyStatus,
  } = buildAppControllerLoaders({
    activeFormId,
    bootstrap,
    currentUser,
    detailLoading,
    escalaDetails,
    responseDetails,
    setActiveFormId,
    setBootstrap,
    setDetailLoading,
    setError,
    setEscalaDetails,
    setFormDeleteKeyConfigured,
    setLoading,
    setResponseDetails,
  });

  const {
    adminHandlers,
    eventHandlers,
    formHandlers,
    sessionHandlers,
  } = buildAppControllerHandlers({
    activeForm,
    activeEventId,
    currentUser,
    events,
    refreshBootstrap,
    refreshEscalaForForm,
    setActiveEventId,
    setActiveFormId,
    setActiveMessageId,
    setBootstrap,
    setDraftForm,
    setEditingFormId,
    setEscalaDetails,
    setFontScale,
    setFormDeleteKeyConfigured,
    setPinnedEventsByUser,
    setPinnedFormsByUser,
    setResponseDetails,
    setScreen,
    setSession,
  });
  const {
    invalidateSession,
    navigate,
  } = sessionHandlers;

  useAppControllerLifecycle({
    activeForm,
    authToken,
    currentUser,
    detailLoading,
    error,
    escalaByForm,
    fontScale,
    invalidateSession,
    loadEscalaForForm,
    loadResponsesForForm,
    pinnedEventsByUser,
    pinnedFormsByUser,
    publicForm,
    publicResultsView,
    refreshBootstrap,
    refreshFormDeleteKeyStatus,
    responsesByForm,
    screen,
    session,
    setFontScale,
    setPublicRoute,
    setScreen,
    setSession,
    setTheme,
    theme,
  });

  return buildAppControllerViewModel({
    adminHandlers,
    activeEvent,
    activeEventId,
    activeForm,
    activeMessageId,
    canCreateForms,
    currentUser,
    draftForm,
    editingForm,
    error,
    escalaByForm,
    eventHandlers,
    events,
    externalBases,
    fieldCatalog,
    fontScale,
    formDeleteKeyConfigured,
    formHandlers,
    forms,
    labels,
    loading,
    membersConfig,
    messageTemplates,
    messagingConfig,
    navigate,
    people,
    personPresets,
    pinnedEventIds,
    pinnedFormIds,
    presets,
    publicForm,
    publicResultsEnabled,
    publicResultsView,
    publicRoute,
    refreshBootstrap,
    responsesByForm,
    scaleTaskCatalog,
    screen,
    sessionHandlers,
    setActiveEventId,
    setActiveFormId,
    setActiveMessageId,
    setDraftForm,
    setEditingFormId,
    setPublicRoute,
    setScreen,
    setTheme,
    theme,
    users,
  });
};
